"""add index on datetime to post

Revision ID: e3b0a9446799
Revises: 5a9f1fdf8ce3
Create Date: 2020-06-30 14:17:04.224146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b0a9446799'
down_revision = '5a9f1fdf8ce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_created_on'), 'post', ['created_on'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_created_on'), table_name='post')
    # ### end Alembic commands ###
